funding.json
graphile/graphile.github.io pull request #424
Opened 2024-12-05 10:22 UTC by jemgillam

## Description

I have begun a `funding.json` file. I have kept the comments in it for now, but they will need removing before the final merge into the codebase. Some well-known links will need to be created across our websites. Moved from https://github.com/graphile/crystal/pull/2268

~I chose Graphile Worker and PostGraphile as our projects, we can add more, but I feel Grafast might be too new. The whole thing links to Graphile as an organisation any way.~

I put in our plans from $100/mo and above.

See [floss.fund/funding-manifest](https://floss.fund/funding-manifest/)

This is a new initiative from [zerodha.tech](https://zerodha.tech/)
They launched it last month, the first funding cycle from them is going to start in the new year.

If this initiative gets momentum, then it is worth having a funding.json file anyway, even if FLOSS/fund don't grant us any sponsorship.

Here is a directory of others who have already set this up: [dir.floss.fund/browse/projects](https://dir.floss.fund/browse/projects)

Here are the tags we can choose from for our projects: [floss.fund/static/project-tags.txt](https://floss.fund/static/project-tags.txt)

## To Do 

- [ ] well-known URIs for 
-- [ ] worker.graphile.org
-- [ ] postgraphile.org
-- [ ] grafast.org
-- [ ] graphile.org
- [ ] include all projects over x stars / downloads

2024-12-05 16:45 UTC, jemgillam commented
I have added the funding-manifest files to various of our websites

@Benjie am I right in thinking the GitHub repos need them too?

2024-12-06 11:12 UTC, jemgillam commented
To add to the above, vue.js have one here https://github.com/vuejs/core/blob/main/.well-known/funding-manifest-urls

I have no idea if this works as intended, but it is shown on the FOSS/fund directory as so: https://dir.floss.fund/view/project/@vuejs.org/vuejs

2024-12-06 18:52 UTC, benjie commented
Good research; go with that... I guess?

2024-12-09 16:05 UTC, jemgillam commented
To add onto links for the repos, I have decided to link to  
```
https://github.com/graphile/crystal/tree/main/graphile-build/graphile-build/.well-known/funding-manifest-urls
```
rather than  
```
https://raw.githubusercontent.com/graphile/crystal/tree/main/graphile-build/graphile-build/.well-known/funding-manifest-urls
```
even though the second link is purely the file, the domain is different and so isn't exactly what is required. This approach seems to work for other projects :shrug:

2024-12-10 10:57 UTC, jemgillam commented
@benjie ready to look over. I am adding a readme to `crystal/utils` for the "star" collection of tools/utilities sometime today.

I think we want to discuss some of the wording for the descriptions

2024-12-18 17:18 UTC, benjie requested changes

2024-12-18 17:18 UTC, benjie commented on funding.json
> +    "description": "At Graphile we love GraphQL so much we named ourselves for our love of it!",
```suggestion
    "description": "Devtools for Node.js, PostgreSQL and GraphQL focussed on development and execution efficiency.",
```

2024-12-18 17:18 UTC, benjie commented on funding.json
> +        "description": "A group of useful Graphile utilities, including graphile-config which provides a standard plugin interface and helpers which can be used across the entire Graphile suite; grap
```suggestion
        "description": "A collection of utility modules including: graphile-config (standardized plugins and presets infrastructure); graphile-export (export a dynamic GraphQL Schema as executable JavaScript); tamedevil (makes dealing with `eval` safer); pg-sql2 (SQLi-resistant and speedy SQL templating in Node.js) and pg-introspection.",
```

2024-12-18 17:18 UTC, benjie commented on funding.json
> +        "description": "Job queue for PostgreSQL running on Node.js - allows you to run jobs (e.g. sending emails, performing calculations, generating PDFs, etc) in the background so that your HTTP r
```suggestion
        "description": "Node.js job queue powered by PostgreSQL - schedule jobs (sending emails, converting images, generating PDFs, etc) in the background so your website and API requests don't have to wait.",
```

2024-12-18 17:28 UTC, merged

2024-12-18 17:47 UTC, jemgillam commented
https://dir.floss.fund/submit gives an error, so a `well-known` URI is also needed on graphile.org? I don't know if that makes sense from their descriptions... 

```
entity.webpageUrl.url and manifest URL host and paths do not match. Expected entity.webpageUrl.wellKnown for provenance check at https://graphile.org/*/.well-known/funding-manifest-urls
```